# Generated by Django 6.1.1 on 2026-09-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=150)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sinopsis', models.TextField()),
                ('estreno', models.BooleanField(default=False)),
                ('imagen', models.CharField(help_text='Ruta relativa dentro de static/img/, ej: cine/inception.jpg', max_length=255)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='cine.genero', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-anio'],
            },
        ),
    ]
